# Generated by Django 3.1 on 2020-08-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200817_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_dtae',
            new_name='post_date',
        ),
    ]
