# Generated by Django 3.1 on 2020-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20200819_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='CLick the link above to read the blog post', max_length=255),
        ),
    ]
